//auto generated by MultipleTemplatesMenuItemGenerator.cs

using UnityEditor;

namespace AwesomeSnippets {

	[InitializeOnLoad]
	public static class MultipleTemplatesMenuItem {
		private static ScriptTemplateSettings settings;

		static MultipleTemplatesMenuItem() {
			string[] vs = AssetDatabase.FindAssets("t:ScriptTemplateSettings");

			if (vs.Length > 0) {
				settings = AssetDatabase.LoadAssetAtPath<ScriptTemplateSettings>(AssetDatabase.GUIDToAssetPath(vs[0]));
			}
		}

		[MenuItem("Assets/Create/Snippets Template", false, 80)]
		private static void CreateScriptSnippetsTemplate() {
			if (settings.Templates[0]) {
				string templatePath = AssetDatabase.GetAssetPath(settings.Templates[0]);
				ProjectWindowUtil.CreateScriptAssetFromTemplateFile(templatePath, "SnippetsTemplate.cs");
			}
		}

	}
}